name: Nextflow CI

on:
  push:
  pull_request:

env:
  NXF_ANSI_LOG: false
  NXF_SINGULARITY_CACHEDIR: ${{ github.workspace }}/.singularity
  NXF_SINGULARITY_LIBRARYDIR: ${{ github.workspace }}/.singularity

jobs:
  test:
    name: Test Nextflow ${{ matrix.nextflow_version }} with ${{ matrix.profile }}
    runs-on: ['ubuntu-latest', 'macOS']

    strategy:
      matrix:
        nextflow_version: ['25.04.4', 'latest-everything']
        profile: ['apptainer', 'docker', 'conda']

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Nextflow
        uses: nf-core/setup-nextflow@v2
        with:
          version: ${{ matrix.nextflow_version }}

      - name: Setup Apptainer (если выбран профиль apptainer)
        if: matrix.profile == 'apptainer'
        uses: eWaterCycle/setup-apptainer@main
    
      - name: Set up Miniconda
        if: matrix.profile == 'conda'
        uses: conda-incubator/setup-miniconda@a4260408e20b96e80095f42ff7f1a15b27dd94ca # v3
        with:
          miniconda-version: "latest"
          auto-update-conda: true
          conda-solver: libmamba
          channels: conda-forge,bioconda

      - name: Set up Conda
        if: matrix.profile == 'conda'
        run: |
          echo $(realpath $CONDA)/condabin >> $GITHUB_PATH
          echo $(realpath python) >> $GITHUB_PATH

      - name: Clean up Disk space
        uses: jlumbroso/free-disk-space@54081f138730dfa15788a46383842cd2f914a1be # v1.3.1

      - name: Run Nextflow pipeline
        run: nextflow run main.nf -profile ${{ matrix.profile }}
