name: Nextflow CI

on:
  push:
  pull_request:

env:
  NXF_ANSI_LOG: false
  NXF_SINGULARITY_CACHEDIR: ${{ github.workspace }}/.singularity
  NXF_SINGULARITY_LIBRARYDIR: ${{ github.workspace }}/.singularity

jobs:
  test:
    name: Test Nextflow ${{ matrix.nextflow_version }} with ${{ matrix.profile }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        nextflow_version: ['25.04.4', '24.04.1']   # добавь нужные версии
        profile: ['apptainer', 'docker']

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Nextflow
        uses: nf-core/setup-nextflow@v2
        with:
          version: ${{ matrix.nextflow_version }}

      - name: Setup Apptainer (если выбран профиль apptainer)
        if: matrix.profile == 'apptainer'
        uses: eWaterCycle/setup-apptainer@main

      - name: Run Nextflow pipeline
        run: nextflow run main.nf -profile ${{ matrix.profile }}
