name: Nextflow CI

on:
  push:
  pull_request:

env:
  NXF_ANSI_LOG: false
  NXF_SINGULARITY_CACHEDIR: ${{ github.workspace }}/.singularity
  NXF_SINGULARITY_LIBRARYDIR: ${{ github.workspace }}/.singularity

jobs:
  test:
    name: Test with ${{ matrix.engine }} / Nextflow ${{ matrix.nextflow }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        engine: [docker, apptainer]
        nextflow: ['22.10.0', '23.10.0']

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Install Nextflow ${{ matrix.nextflow }}
        run: |
          curl -s https://get.nextflow.io | bash
          chmod +x nextflow
          sudo mv nextflow /usr/local/bin/
          nextflow self-update ${{ matrix.nextflow }}
          nextflow -version

      - name: Install Apptainer (only if needed)
        if: matrix.engine == 'apptainer'
        uses: eWaterCycle/setup-apptainer@main

      - name: Run Nextflow with ${{ matrix.engine }}
        run: |
          nextflow run main.nf -profile ${{ matrix.engine }}
