name: Nextflow CI

on:
  push:
  pull_request:

env:
  NXF_ANSI_LOG: false
  NXF_SINGULARITY_CACHEDIR: ${{ github.workspace }}/.singularity
  NXF_SINGULARITY_LIBRARYDIR: ${{ github.workspace }}/.singularity

jobs:
  test-apptainer:
    name: Test with Apptainer
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Nextflow
        uses: nf-core/setup-nextflow@v2

      - name: Install Apptainer
        uses: eWaterCycle/setup-apptainer@main

      - name: Run Nextflow with apptainer
        run: nextflow run main.nf -profile apptainer

  test-docker:
    name: Test with Docker
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Nextflow
        uses: nf-core/setup-nextflow@v2

      - name: Run Nextflow with docker
        run: nextflow run main.nf -profile docker
